### ISSUE TITLE
[FEAT] - Add  background on button

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#60]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
On the "connect with me button", add a background and text color on the `btn-secondary` class.
You can find this button class in `utilities.css`

```css
.btn-secondary {
  background: var(--bg-secondary);
  color: var(--text-color-2);
}
```

## Screenshots
![button-background](https://user-images.githubusercontent.com/62628408/150540592-11aac6c5-e7e0-4083-923e-ae3ccc55a44d.png)

## Describe alternatives you've considered
None

## Additional context
It's good to note that the `--bg-secondary` & `--text-color-2` classes are responsible for adding the background and text color on both the light and dark mode.
