### ISSUE TITLE
[FEAT] - Make project cards responsive

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/portfolio-html#86]
## Is your feature request related to a problem? Please describe.
Projects cards are not mobile responsive.

## Describe the solution you'd like
Make the cards responsive. The cards are currently using `grid` which is added to the project `class` in the `style.css` file

## Describe alternatives you've considered
The cards are currently in 3 columns and two rows, using `media-queries`, add a new breakpoint at `1000px` to make the cards two columns and at `600px` one column.

## Fix
```css
@media (max-width: 1000px) {
  .project {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (max-width: 600px) {
  .project {
    display: grid;
    grid-template-columns: 1fr;
  }
}
```

Also, in the `style.css` file, try to arrange the `media-queries` according to their breakpoints -where `1000px` is first and `600px` is last.

Each breakpoint can be handled by two persons. 
- [x] #87
- [x] #88
